version: "3"

services:

  prod_app:
    image: bsielski/single-page-contacts:1.0.0
    #build:
      #context: ..
      #dockerfile: ./docker-production/Dockerfile
    expose:
      - 3000
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d/default.conf
    env_file: ./.env-app
    networks:
      - net-pg
      - default

  prod_webserver:
    image: nginx:1.13.12-alpine
    volumes:
      - assets:/usr/share/nginx/html
      - configs:/etc/nginx/conf.d
    expose:
      - 80
    env_file: ./.env-webserver
    networks:
      - net-80
      - default
    depends_on:
      - prod_app

volumes:
  assets:
  configs:

networks:
  net-80:
    external:
      name: net-80
  net-pg:
    external:
      name: net-pg
