version: "3"

services:

  app:
    image: bsielski/single-page-contacts:1.0.0
    #build:
      #context: ..
      #dockerfile: ./docker-production/Dockerfile
    expose:
      - 3000
    #volumes:
      #- assets:/usr/share/nginx/html
      #- configs:/etc/nginx/conf.d/default.conf
    env_file: ./.env-app
    networks:
      - net-pg
      - default

  webserver:
    image: nginx:1.13.12-alpine
    volumes:
      #- assets:/usr/share/nginx/html
      #- configs:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: ./.env-webserver
    networks:
      - rev-proxy
      - default
    depends_on:
      - app

#volumes:
  #assets:
  #configs:

networks:
  rev-proxy:
    external:
      name: rev-proxy
  net-pg:
    external:
      name: net-pg
